# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  random_number_generator_config = debug
endif
ifeq ($(config),release)
  random_number_generator_config = release
endif

PROJECTS := random_number_generator

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

random_number_generator:
ifneq (,$(random_number_generator_config))
	@echo "==== Building random_number_generator ($(random_number_generator_config)) ===="
	@${MAKE} --no-print-directory -C . -f random_number_generator.make config=$(random_number_generator_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f random_number_generator.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   random_number_generator"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"